### ISSUE TITLE
Problems with github token

### ISSUE THREAD

**Issue by robinjhector** [hmarr/auto-approve-action#187] opened 2021-04-12 10:30 UTC
Hi, I'm getting this error when attempting to run auto-approve for dependabot PRs. The full workflow:

```yml
name: "Auto approve Dependabot updates"

on: pull_request

jobs:
  approve:
    name: Auto approve dependabot pull requests
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```

The `GITHUB_TOKEN` secret is the default actions token.
But I'm getting the following output:

```
Run hmarr/auto-approve-action@v2
  with:
    github-token: ***
Creating approving review for pull request #51
Error: Resource not accessible by integration. In some cases, the GitHub token used for actions triggered from `pull_request` events are read-only, which can cause this problem. Switching to the `pull_request_target` event typically resolves this issue.
```

I seem to remember this working before. Not sure what has changed. Any ideas?

**Comment by hmarr** [comment] 2021-04-12 14:28
Did you try switching to the `pull_request_target` event that the error message mentions? #183 contains a lot of additional context.

**Comment by hmarr** [comment] 2021-04-13 15:11
Closing this for now as I assume it's a duplicate of #183, but feel free to reopen if the suggested change doesn't fix the problem!

**Closed as completed by hmarr** 2021-04-13 15:11 UTC
